version: '3.8'

services:
  app:
    build: ./backend
    container_name: backend-juridico
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_scripts:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"

volumes:
  postgres_data: